const EN = {
    Login: "Login",
    eMail: "e-mail",
    password: "Password",
    passwordLength: "*must be at least 6 characters",
    signUp: "Sign Up",
    serverError: "Server access error",
    unknowError: "Unknow Error",
    invalidEmail: "Invalid e-mail",
    IncorrectEmail: "Incorrect email",
    MinimumPasswordLength6Characters: "Minimum password length 6 characters",
    IncorrectRegistrationData: "Incorrect registration data",
    ThisUserAlreadyExists: "This user already exists",
    UserCreated: "User created",
    SomethingWentWrongTryAgain: "Something went wrong, try again",
    PleaseEnterAValidEmail: "Please enter a valid email",
    EnterPassword: "Enter password",
    InvalidLoginData: "Invalid login data",
    UserIsNotFound: "User is not found",
    InvalidPasswordTryAgain: "Invalid password, try again",
    NoAuthorization: "No authorization",
    time: "Time",
    name: "Name",
    ducks: "Ducks",
    hits: "Shots",
    persent: "Persent",
    score: "Score",
    statisticsTable: "Statistics table",
    gameMenu: "Game menu",
    game: "Game",
    pause: "pause",
    continue: "continue",
    level: "level",
    start: "Start",
    levels: "Levels",
    settings: "Settings",
    statistic: "Statistic",
    lvl: "lvl.",
    back: "back",
    badHuntDude: "Bad hunt Dude!",
    awesomeHunter: "Awesome hunter",
    close: "Close",
    detecting: "Detecting...",
    ducksAreDetected: "Ducks are detected! Click here...",
    totalScoreTable: "Total score table",
    win: "You win",
    tonia: "Antonina Zinkevich",
    sergey: "Sergey Nesterov",
    fedos: "Fedor Mikulich",
    andrey: "Andrey Komov",
    panLeft: "L",
    panRight: "R",
    theme: "Theme",
    standart: "Standart",
    pencil: "Pencil draw",
    vision: "Night vision",
    night: "Night",
    continueWithoutRegistration: "Continue without registration",
    loginAs: "Login as",
    hello: "Hello",
    foreverAlone: "Forever alone"
};
const RU = {
    Login: "Вход",
    eMail: "e-mail",
    password: "Пароль",
    passwordLength: "*должен быть не менее 6 символов",
    signUp: "Рег.",
    serverError: "Ошибка доступа к серверу",
    unknowError: "Неизвестная ошибка",
    invalidEmail: "Неверный e-mail",
    IncorrectEmail: "Некорректный email",
    MinimumPasswordLength6Characters: "Минимальная длина пароля 6 символов",
    IncorrectRegistrationData: "Некорректные данные при регистрации",
    ThisUserAlreadyExists: "Такой пользователь уже существует",
    UserCreated: "Пользователь создан",
    SomethingWentWrongTryAgain: "Что-то пошло не так, попробуйте снова",
    PleaseEnterAValidEmail: "Введите корректный email",
    EnterPassword: "Введите пароль",
    InvalidLoginData: "Некорректный данные при входе в систему",
    UserIsNotFound: "Пользователь не найден",
    InvalidPasswordTryAgain: "Неверный пароль, попробуйте снова",
    NoAuthorization: "Не авторизован",
    time: "Время",
    name: "Имя",
    ducks: "Уток",
    hits: "Попаданий",
    persent: "Процент",
    score: "Очки",
    statisticsTable: "Таблица статистики",
    gameMenu: "Игровое меню",
    game: "Игра",
    pause: "пауза",
    continue: "продолжить",
    level: "уровень",
    start: "Старт",
    levels: "Уровни",
    settings: "Настройки",
    statistic: "Статистика",
    lvl: "Ур.",
    back: "назад",
    badHuntDude: "Плохая охота, чувак!",
    awesomeHunter: "Замечательный охотник",
    close: "Закрыть",
    detecting: "Обнаружение ...",
    ducksAreDetected: "Утки обнаружены! Нажмите здесь ...",
    totalScoreTable: "Сводная таблица",
    win: "Победа",
    tonia: "Антонина Зинкевич",
    sergey: "Сергей Нестеров",
    fedos: "Федор Микулич",
    andrey: "Андрей Комов",
    panLeft: "Л",
    panRight: "П",
    theme: "Тема",
    standart: "Стандартная",
    pencil: "Простой карандащ",
    vision: "Ночное видение",
    night: "Ночь",
    continueWithoutRegistration: "Продолжить без регистрации",
    loginAs: "Войти как",
    hello: "Привет",
    foreverAlone: "Вечно одинок"
};

const BY = {
    Login: "Уваход",
    eMail: "e-mail",
    password: "Пароль",
    passwordLength: "*павінен быць не менш за 6 сімвалаў",
    signUp: "Рэгістрацыя",
    serverError: "Памылка доступу да сервера",
    unknowError: "Невядомая памылка",
    invalidEmail: "Няправільны e-mail",
    IncorrectEmail: "Некарэктны email",
    MinimumPasswordLength6Characters: "Мінімальная даўжыня пароля 6 сімвалаў",
    IncorrectRegistrationData: "Некарэктныя дадзеныя пры рэгістрацыі",
    ThisUserAlreadyExists: "Такі карыстач ужо існуе",
    UserCreated: "Карыстач створаны",
    SomethingWentWrongTryAgain: "Нешта пайшло не так, паспрабуйце зноў",
    PleaseEnterAValidEmail: "Увядзіце карэктны email",
    EnterPassword: "Увядзіце пароль",
    InvalidLoginData: "Некарэктны дадзеныя пры ўваходзе ў сістэму",
    UserIsNotFound: "Карыстач не знойдзены",
    InvalidPasswordTryAgain: "Няправільны пароль, паспрабуйце зноў",
    NoAuthorization: "Не аўтарызаваны",
    time: "Час",
    name: "Імя",
    ducks: "Качак",
    hits: "Трапленняў",
    persent: "Адсоткаў",
    score: "Ачкі",
    statisticsTable: "Табліца статыстыкі",
    gameMenu: "Гульнёвае меню",
    game: "Гульня",
    pause: "паўза",
    continue: "працягваць",
    level: "узровень",
    start: "Старт",
    levels: "Узроўні",
    settings: "Настройкі",
    statistic: "Статыстыка",
    lvl: "узр.",
    back: "назад",
    badHuntDude: "Кепскае паляванне, чувак!",
    awesomeHunter: "Выдатны паляўнічы",
    close: "Зачынiць",
    detecting: "Выяўленне ...",
    ducksAreDetected: "Качкі выяўленыя! Націсніце тут ...",
    totalScoreTable: "Зводная табліца",
    win: "Перамога",
    tonia: "Антанiна Зiнкевiч",
    sergey: "Сяргей Несцераў",
    fedos: "Федар Мiкулiч",
    andrey: "Андрэй Комаў",
    panLeft: "Л",
    panRight: "П",
    theme: "Тэма",
    standart: "стандартная",
    pencil: "просты аловак",
    vision: "начное бачанне",
    night: "ноч",
    continueWithoutRegistration: "Працягнуць без рэгістрацыі",
    loginAs: "Увайсці як",
    hello: "Прывитанне",
    foreverAlone: "Вечна адзінокі"
};

export const lang = {
    EN,
    RU,
    BY
};

let currentLang = "RU";
export function getLang() {
    return currentLang;
}
export function setLang(l) {
    currentLang = l;
}
